name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    if: ${{ !contains(github.ref_name, '-beta') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --no-interaction
      - run: composer test --no-interaction
